name: Slack Notification
description: 'Send Slack notification'

runs:
  using: 'composite'
  steps:
    - id: 'notify'
      shell: bash
      run: |
        payload="{\"report\":\"Banner Manager deploy success\"}"
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$payload" \
          https://hooks.slack.com/triggers/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